import type { SlopeNode, Alert, MethodologyStep, TechStackTile, ResearchSource, ImpactEvent, LanguageOption } from '../types';

export const DEFAULT_DEMO_PHONE_NUMBER = '+91 6300156232';

export interface HamletZoneOption {
  id: string;
  name: string;
  district: string;
  state: string;
  riskScore: number;
  status: 'SAFE' | 'WATCH' | 'DANGER';
}

export const HAMLET_ZONES: HamletZoneOption[] = [
  // Meghalaya
  { id: 'h-sohra', name: 'Sohra (Cherrapunji)', district: 'East Khasi Hills', state: 'Meghalaya', riskScore: 87, status: 'DANGER' },
  { id: 'h-mawlynnong', name: 'Mawlynnong Slope', district: 'East Khasi Hills', state: 'Meghalaya', riskScore: 29, status: 'SAFE' },
  { id: 'h-nongpoh', name: 'Nongpoh Transit Corridor', district: 'Ri-Bhoi', state: 'Meghalaya', riskScore: 55, status: 'WATCH' },
  { id: 'h-jowai', name: 'Jowai Coal Belt Slope', district: 'West Jaintia Hills', state: 'Meghalaya', riskScore: 68, status: 'WATCH' },
  { id: 'h-tura', name: 'Tura Peak Corridor', district: 'West Garo Hills', state: 'Meghalaya', riskScore: 63, status: 'WATCH' },

  // Nagaland
  { id: 'h-khonoma', name: 'Khonoma Village', district: 'Kohima', state: 'Nagaland', riskScore: 62, status: 'WATCH' },
  { id: 'h-mokokchung', name: 'Mokokchung Town Ridge', district: 'Mokokchung', state: 'Nagaland', riskScore: 48, status: 'SAFE' },
  { id: 'h-wokha', name: 'Wokha Hydro Catchment', district: 'Wokha', state: 'Nagaland', riskScore: 66, status: 'WATCH' },
  { id: 'h-mon', name: 'Mon Konyak Hills', district: 'Mon', state: 'Nagaland', riskScore: 77, status: 'DANGER' },
  { id: 'h-tuensang', name: 'Tuensang High Pass', district: 'Tuensang', state: 'Nagaland', riskScore: 69, status: 'WATCH' },

  // Arunachal Pradesh
  { id: 'h-ziro', name: 'Ziro Valley', district: 'Lower Subansiri', state: 'Arunachal Pradesh', riskScore: 24, status: 'SAFE' },
  { id: 'h-tawang', name: 'Tawang Monastery Pass', district: 'Tawang', state: 'Arunachal Pradesh', riskScore: 83, status: 'DANGER' },
  { id: 'h-namtso', name: 'Namtso Ridge', district: 'West Kameng', state: 'Arunachal Pradesh', riskScore: 73, status: 'WATCH' },
  { id: 'h-pasighat', name: 'Pasighat Siang Bank', district: 'East Siang', state: 'Arunachal Pradesh', riskScore: 58, status: 'WATCH' },
  { id: 'h-tezu', name: 'Tezu Lohit Valley', district: 'Lohit', state: 'Arunachal Pradesh', riskScore: 64, status: 'WATCH' },

  // Mizoram
  { id: 'h-relek', name: 'Relek', district: 'Aizawl', state: 'Mizoram', riskScore: 18, status: 'SAFE' },
  { id: 'h-champhai', name: 'Champhai Border Ridge', district: 'Champhai', state: 'Mizoram', riskScore: 79, status: 'DANGER' },
  { id: 'h-lunglei', name: 'Lunglei South Ridge', district: 'Lunglei', state: 'Mizoram', riskScore: 71, status: 'WATCH' },
  { id: 'h-serchhip', name: 'Serchhip Valley Sector', district: 'Serchhip', state: 'Mizoram', riskScore: 42, status: 'SAFE' },

  // Manipur
  { id: 'h-ukhrul', name: 'Ukhrul East Ridge', district: 'Ukhrul', state: 'Manipur', riskScore: 81, status: 'DANGER' },
  { id: 'h-tamenglong', name: 'Tamenglong Gorge', district: 'Tamenglong', state: 'Manipur', riskScore: 76, status: 'DANGER' },
  { id: 'h-churachandpur', name: 'Churachandpur Hill Sector', district: 'Churachandpur', state: 'Manipur', riskScore: 52, status: 'WATCH' },
  { id: 'h-senapati', name: 'Senapati Highway Pass', district: 'Senapati', state: 'Manipur', riskScore: 67, status: 'WATCH' },

  // Assam & Tripura
  { id: 'h-haflong', name: 'Haflong Hill Station', district: 'Dima Hasao', state: 'Assam', riskScore: 85, status: 'DANGER' },
  { id: 'h-diphu', name: 'Diphu Valley Corridor', district: 'Karbi Anglong', state: 'Assam', riskScore: 41, status: 'SAFE' },
  { id: 'h-jampui', name: 'Jampui Hills Ridge', district: 'North Tripura', state: 'Tripura', riskScore: 59, status: 'WATCH' },
  { id: 'h-unakoti', name: 'Unakoti Slope Zone', district: 'Unakoti', state: 'Tripura', riskScore: 34, status: 'SAFE' },

  // Sikkim & West Bengal
  { id: 'h-gangtok', name: 'Gangtok Cliff Pass', district: 'East Sikkim', state: 'Sikkim', riskScore: 74, status: 'WATCH' },
  { id: 'h-mangan', name: 'Mangan North Highway', district: 'North Sikkim', state: 'Sikkim', riskScore: 89, status: 'DANGER' },
  { id: 'h-darjeeling', name: 'Darjeeling Tea Ridge', district: 'Darjeeling', state: 'West Bengal', riskScore: 82, status: 'DANGER' },
  { id: 'h-kalimpong', name: 'Kalimpong Transit Slope', district: 'Kalimpong', state: 'West Bengal', riskScore: 78, status: 'DANGER' },
];

export const FEASIBILITY_SNAPSHOTS = [
  { id: 1, title: 'Low CapEx Deployment', text: 'Uses solar-powered off-grid LoRaWAN mesh nodes ($45 each) vs expensive traditional $50k stations.' },
  { id: 2, title: 'Zero-Downtime Resilience', text: 'Multi-path mesh network re-routes packet streams around mountain peaks during severe monsoon blackouts.' },
  { id: 3, title: 'Institutional Compatibility', text: 'Integrates natively with NDMA, SDMA, and GSI early warning dissemination protocols.' },
];

export const RISK_MITIGATION_ROWS = [
  { id: 1, risk: 'Monsoon Power Grid Blackouts', fix: 'Dual solar + supercapacitor power buffer with 14-day zero-sunlight autonomy.' },
  { id: 2, risk: 'Cellular Tower Failures in High Altitude', fix: 'LoRaWAN peer-to-peer mesh hops telemetry packets up to 18km without cellular towers.' },
  { id: 3, risk: 'Language & Literacy Barriers', fix: 'Automated PSTN IVR phone calls deliver voice warnings in 19,569 local dialects.' },
  { id: 4, risk: 'Satellite InSAR Pass Latency (6-Day Orbit)', fix: 'Continuous ground piezometers & volunteer foot patrol app bridge real-time gap.' },
];

export const IMPACT_TIMELINE_EVENTS: ImpactEvent[] = [
  { time: '00:00', title: 'Ground Sensor Creep Spike', subtitle: 'Displacement exceeds 10mm threshold at Sohra', statusBadge: 'Spike Detected', badgeType: 'DANGER' },
  { time: '+02s', title: 'InSAR Satellite Fusion', subtitle: 'Sentinel-1 radar confirms 14.6mm movement', statusBadge: 'SAR Confirmed', badgeType: 'QUEUED' },
  { time: '+05s', title: 'AI Risk Surge to 87/100', subtitle: 'Pore pressure & slope creep trigger DANGER score', statusBadge: 'AI Triggered', badgeType: 'QUEUED' },
  { time: '+12s', title: 'Hyper-Local IVR Call Dispatched', subtitle: 'Automated voice calls ring physical mobile phones in Khasi', statusBadge: 'Calls Dispatched', badgeType: 'SENT' },
];

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'kha', name: 'Khasi', nativeName: 'Ka Ktien Khasi' },
  { code: 'pna', name: 'Pnar / Jaintia', nativeName: 'Ka Ktien Pnar' },
  { code: 'lus', name: 'Mizo', nativeName: 'Mizo ṭawng' },
  { code: 'hma', name: 'Hmar', nativeName: 'Hmar ṭawng' },
  { code: 'njz', name: 'Nyishi', nativeName: 'Nyishi Agam' },
  { code: 'apa', name: 'Apatani', nativeName: 'Tanii Agam' },
  { code: 'gal', name: 'Galo', nativeName: 'Galo Agam' },
  { code: 'adi', name: 'Adi', nativeName: 'Adi Agam' },
  { code: 'grt', name: 'Garo', nativeName: 'A·chik Ku·sik' },
  { code: 'mni', name: 'Manipuri / Meitei', nativeName: 'মৈতৈলোন্' },
  { code: 'tan', name: 'Tangkhul Naga', nativeName: 'Tangkhul Tui' },
  { code: 'nag', name: 'Nagamese Creole', nativeName: 'Nagamese' },
  { code: 'ang', name: 'Angami Naga', nativeName: 'Tenyidie' },
  { code: 'ao', name: 'Ao Naga', nativeName: 'Ao Opar' },
  { code: 'sum', name: 'Sumi Naga', nativeName: 'Sümi Tsakheh' },
  { code: 'lot', name: 'Lotha Naga', nativeName: 'Lotha Yena' },
  { code: 'kon', name: 'Konyak Naga', nativeName: 'Konyak' },
  { code: 'trv', name: 'Kokborok', nativeName: 'Kokborok' },
  { code: 'rea', name: 'Reang / Bru', nativeName: 'Kau Bru' },
  { code: 'brx', name: 'Bodo', nativeName: "बर'" },
  { code: 'kar', name: 'Karbi', nativeName: 'Karbi Lam' },
  { code: 'dim', name: 'Dimasa', nativeName: 'Dimasa Grao' },
  { code: 'lep', name: 'Lepcha', nativeName: 'Róng Ríng' },
  { code: 'bhu', name: 'Bhutia', nativeName: 'Denzongke' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'కన్నడ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

export const INITIAL_SLOPE_NODES: SlopeNode[] = [
  // MEGHALAYA
  {
    id: 'node-sohra',
    name: 'Sohra (Cherrapunji)',
    state: 'Meghalaya',
    district: 'East Khasi Hills',
    lat: 25.27,
    lng: 91.73,
    riskScore: 87,
    status: 'DANGER',
    type: 'hamlet',
    delta: '-5% vs yesterday',
    lastUpdated: '30s ago',
    sensors: { groundSensors: 26, satelliteFeeds: 3, weatherStations: 1, communityReports: 9 },
    displacementMm: 14.6,
    rainfallMm24h: 245,
    soilMoisturePct: 91,
    vibrationHz: 1.82,
    connectedNodes: ['node-khonoma', 'node-ivr', 'node-jowai', 'node-tura'],
    recentAlerts: ['CRITICAL: Evacuation IVR Call placed in Khasi & Pnar', 'High pore pressure: 91% saturation', 'Siren triggered at village headman house'],
  },
  {
    id: 'node-tura',
    name: 'Tura Peak',
    state: 'Meghalaya',
    district: 'West Garo Hills',
    lat: 25.51,
    lng: 90.22,
    riskScore: 63,
    status: 'WATCH',
    type: 'hamlet',
    delta: '+4% vs yesterday',
    lastUpdated: '5 mins ago',
    sensors: { groundSensors: 18, satelliteFeeds: 2, weatherStations: 1, communityReports: 7 },
    displacementMm: 5.1,
    rainfallMm24h: 112,
    soilMoisturePct: 71,
    vibrationHz: 0.52,
    connectedNodes: ['node-sohra', 'node-ivr'],
    recentAlerts: ['Creep rate elevated on West slope'],
  },
  {
    id: 'node-jowai',
    name: 'Jowai Ridge',
    state: 'Meghalaya',
    district: 'West Jaintia Hills',
    lat: 25.44,
    lng: 92.20,
    riskScore: 68,
    status: 'WATCH',
    type: 'hamlet',
    delta: '+8% vs yesterday',
    lastUpdated: '3 mins ago',
    sensors: { groundSensors: 22, satelliteFeeds: 3, weatherStations: 1, communityReports: 11 },
    displacementMm: 6.4,
    rainfallMm24h: 145,
    soilMoisturePct: 76,
    vibrationHz: 0.68,
    connectedNodes: ['node-sohra', 'node-haflong'],
    recentAlerts: ['Pnar dialect alert queued'],
  },

  // ARUNACHAL PRADESH
  {
    id: 'node-ziro',
    name: 'Ziro Valley',
    state: 'Arunachal Pradesh',
    district: 'Lower Subansiri',
    lat: 27.54,
    lng: 93.83,
    riskScore: 24,
    status: 'SAFE',
    type: 'hamlet',
    delta: '+20% vs yesterday',
    lastUpdated: 'Just now',
    sensors: { groundSensors: 32, satelliteFeeds: 3, weatherStations: 1, communityReports: 12 },
    displacementMm: 0.8,
    rainfallMm24h: 12,
    soilMoisturePct: 38,
    vibrationHz: 0.12,
    connectedNodes: ['node-khonoma', 'node-tawang'],
    recentAlerts: ['Routine sensor check ok', 'Zero ground tilt detected'],
  },
  {
    id: 'node-tawang',
    name: 'Tawang Pass',
    state: 'Arunachal Pradesh',
    district: 'Tawang',
    lat: 27.58,
    lng: 91.86,
    riskScore: 83,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+12% vs yesterday',
    lastUpdated: '2 mins ago',
    sensors: { groundSensors: 35, satelliteFeeds: 4, weatherStations: 1, communityReports: 15 },
    displacementMm: 12.8,
    rainfallMm24h: 198,
    soilMoisturePct: 86,
    vibrationHz: 1.45,
    connectedNodes: ['node-ziro', 'node-mangan'],
    recentAlerts: ['Monastery slope tension crack 12.8mm', 'Monpa voice broadcast active'],
  },
  {
    id: 'node-pasighat',
    name: 'Pasighat Siang',
    state: 'Arunachal Pradesh',
    district: 'East Siang',
    lat: 28.06,
    lng: 95.32,
    riskScore: 58,
    status: 'WATCH',
    type: 'hamlet',
    delta: '+3% vs yesterday',
    lastUpdated: '4 mins ago',
    sensors: { groundSensors: 24, satelliteFeeds: 2, weatherStations: 1, communityReports: 8 },
    displacementMm: 4.8,
    rainfallMm24h: 95,
    soilMoisturePct: 62,
    vibrationHz: 0.41,
    connectedNodes: ['node-mon', 'node-ziro'],
    recentAlerts: ['Riverbank erosion monitor active'],
  },

  // NAGALAND
  {
    id: 'node-khonoma',
    name: 'Khonoma',
    state: 'Nagaland',
    district: 'Kohima',
    lat: 25.64,
    lng: 94.02,
    riskScore: 62,
    status: 'WATCH',
    type: 'hub',
    delta: '+10% vs yesterday',
    lastUpdated: '1 min ago',
    sensors: { groundSensors: 42, satelliteFeeds: 4, weatherStations: 1, communityReports: 16 },
    displacementMm: 4.2,
    rainfallMm24h: 78,
    soilMoisturePct: 68,
    vibrationHz: 0.45,
    connectedNodes: ['node-ziro', 'node-relek', 'node-sohra', 'node-ivr', 'node-mon'],
    recentAlerts: ['Voice alert sent via IVR (Angami/Nagamese)', 'Ground tilt variance +4.2mm'],
  },
  {
    id: 'node-mon',
    name: 'Mon Konyak Hills',
    state: 'Nagaland',
    district: 'Mon',
    lat: 26.75,
    lng: 95.05,
    riskScore: 77,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+15% vs yesterday',
    lastUpdated: '2 mins ago',
    sensors: { groundSensors: 30, satelliteFeeds: 3, weatherStations: 1, communityReports: 14 },
    displacementMm: 11.2,
    rainfallMm24h: 185,
    soilMoisturePct: 83,
    vibrationHz: 1.25,
    connectedNodes: ['node-khonoma', 'node-pasighat'],
    recentAlerts: ['Konyak dialect alert broadcast sent'],
  },

  // MIZORAM
  {
    id: 'node-relek',
    name: 'Relek',
    state: 'Mizoram',
    district: 'Aizawl',
    lat: 23.72,
    lng: 92.71,
    riskScore: 18,
    status: 'SAFE',
    type: 'hamlet',
    delta: '-2% vs yesterday',
    lastUpdated: '2 mins ago',
    sensors: { groundSensors: 28, satelliteFeeds: 2, weatherStations: 1, communityReports: 8 },
    displacementMm: 0.3,
    rainfallMm24h: 8,
    soilMoisturePct: 32,
    vibrationHz: 0.08,
    connectedNodes: ['node-khonoma', 'node-ivr', 'node-champhai'],
    recentAlerts: ['Satellite InSAR variance within normal range'],
  },
  {
    id: 'node-champhai',
    name: 'Champhai Ridge',
    state: 'Mizoram',
    district: 'Champhai',
    lat: 23.47,
    lng: 93.32,
    riskScore: 79,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+9% vs yesterday',
    lastUpdated: '1 min ago',
    sensors: { groundSensors: 25, satelliteFeeds: 3, weatherStations: 1, communityReports: 10 },
    displacementMm: 10.8,
    rainfallMm24h: 172,
    soilMoisturePct: 84,
    vibrationHz: 1.15,
    connectedNodes: ['node-relek', 'node-ukhrul'],
    recentAlerts: ['Mizo voice note triggered on emergency mesh'],
  },

  // MANIPUR
  {
    id: 'node-ukhrul',
    name: 'Ukhrul East Ridge',
    state: 'Manipur',
    district: 'Ukhrul',
    lat: 25.11,
    lng: 94.36,
    riskScore: 81,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+11% vs yesterday',
    lastUpdated: '3 mins ago',
    sensors: { groundSensors: 29, satelliteFeeds: 3, weatherStations: 1, communityReports: 13 },
    displacementMm: 12.1,
    rainfallMm24h: 190,
    soilMoisturePct: 88,
    vibrationHz: 1.38,
    connectedNodes: ['node-khonoma', 'node-champhai', 'node-tamenglong'],
    recentAlerts: ['Tangkhul voice warning active'],
  },
  {
    id: 'node-tamenglong',
    name: 'Tamenglong Gorge',
    state: 'Manipur',
    district: 'Tamenglong',
    lat: 24.98,
    lng: 93.49,
    riskScore: 76,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+7% vs yesterday',
    lastUpdated: '5 mins ago',
    sensors: { groundSensors: 22, satelliteFeeds: 2, weatherStations: 1, communityReports: 7 },
    displacementMm: 9.6,
    rainfallMm24h: 165,
    soilMoisturePct: 81,
    vibrationHz: 1.05,
    connectedNodes: ['node-ukhrul', 'node-haflong'],
    recentAlerts: ['Rongmei Naga alert queued'],
  },

  // ASSAM & TRIPURA
  {
    id: 'node-haflong',
    name: 'Haflong Hill',
    state: 'Assam',
    district: 'Dima Hasao',
    lat: 25.17,
    lng: 93.01,
    riskScore: 85,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+14% vs yesterday',
    lastUpdated: '2 mins ago',
    sensors: { groundSensors: 38, satelliteFeeds: 4, weatherStations: 1, communityReports: 18 },
    displacementMm: 13.9,
    rainfallMm24h: 220,
    soilMoisturePct: 89,
    vibrationHz: 1.62,
    connectedNodes: ['node-sohra', 'node-jowai', 'node-tamenglong', 'node-jampui'],
    recentAlerts: ['Railway track slope subsidence alert'],
  },
  {
    id: 'node-jampui',
    name: 'Jampui Hills',
    state: 'Tripura',
    district: 'North Tripura',
    lat: 23.91,
    lng: 92.27,
    riskScore: 59,
    status: 'WATCH',
    type: 'hamlet',
    delta: '+2% vs yesterday',
    lastUpdated: '6 mins ago',
    sensors: { groundSensors: 20, satelliteFeeds: 2, weatherStations: 1, communityReports: 6 },
    displacementMm: 4.5,
    rainfallMm24h: 88,
    soilMoisturePct: 65,
    vibrationHz: 0.38,
    connectedNodes: ['node-haflong', 'node-relek'],
    recentAlerts: ['Kokborok voice alert ready'],
  },

  // SIKKIM
  {
    id: 'node-mangan',
    name: 'Mangan North Highway',
    state: 'Sikkim',
    district: 'North Sikkim',
    lat: 27.51,
    lng: 88.53,
    riskScore: 89,
    status: 'DANGER',
    type: 'hamlet',
    delta: '+18% vs yesterday',
    lastUpdated: '1 min ago',
    sensors: { groundSensors: 40, satelliteFeeds: 4, weatherStations: 1, communityReports: 21 },
    displacementMm: 15.4,
    rainfallMm24h: 260,
    soilMoisturePct: 93,
    vibrationHz: 1.95,
    connectedNodes: ['node-gangtok', 'node-tawang'],
    recentAlerts: ['Teesta river bank slip detected', 'Lepcha/Bhutia warning sent'],
  },
  {
    id: 'node-gangtok',
    name: 'Gangtok Cliff Pass',
    state: 'Sikkim',
    district: 'East Sikkim',
    lat: 27.33,
    lng: 88.61,
    riskScore: 74,
    status: 'WATCH',
    type: 'hamlet',
    delta: '+6% vs yesterday',
    lastUpdated: '3 mins ago',
    sensors: { groundSensors: 31, satelliteFeeds: 3, weatherStations: 1, communityReports: 12 },
    displacementMm: 8.7,
    rainfallMm24h: 155,
    soilMoisturePct: 78,
    vibrationHz: 0.92,
    connectedNodes: ['node-mangan'],
    recentAlerts: ['NH-10 corridor slope watch'],
  },

  // SHILLONG CENTRAL HUB
  {
    id: 'node-ivr',
    name: 'IVR Central Hub',
    state: 'Regional Hub',
    district: 'Shillong Central Relay',
    lat: 25.57,
    lng: 91.88,
    riskScore: 54,
    status: 'WATCH',
    type: 'ivr',
    delta: '+6% vs yesterday',
    lastUpdated: 'Just now',
    sensors: { groundSensors: 0, satelliteFeeds: 0, weatherStations: 0, communityReports: 0 },
    displacementMm: 0,
    rainfallMm24h: 110,
    soilMoisturePct: 55,
    vibrationHz: 0.2,
    connectedNodes: ['node-sohra', 'node-khonoma', 'node-relek', 'node-haflong'],
    recentAlerts: ['Broadcasting 128 automated calls', 'SMS gateway online'],
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-1',
    nodeId: 'node-sohra',
    placeName: 'Sohra (Cherrapunji)',
    status: 'DANGER',
    timestamp: '2 mins ago',
    channel: 'IVR',
    read: false,
    description: {
      en: 'CRITICAL: Slope Creep reached 14.6mm at Sohra Sector. Automated voice warning calls dispatched in Khasi & Pnar.',
      hi: 'गंभीर: सोहरा क्षेत्र में ढलान 14.6 मिमी तक बढ़ गई है। खासी और पनार में स्वचालित आवाज चेतावनी कॉल भेजी गई।',
    },
  },
  {
    id: 'alt-2',
    nodeId: 'node-mangan',
    placeName: 'Mangan North Highway',
    status: 'DANGER',
    timestamp: '5 mins ago',
    channel: 'SIREN',
    read: false,
    description: {
      en: 'Teesta valley bank slip detected (15.4mm creep). Outdoor emergency sirens active across Mangan sector.',
      hi: 'तीस्ता घाटी में भूस्खलन 15.4 मिमी दर्ज। मंगन क्षेत्र में आपातकालीन सायरन चालू।',
    },
  },
  {
    id: 'alt-3',
    nodeId: 'node-haflong',
    placeName: 'Haflong Hill Station',
    status: 'DANGER',
    timestamp: '12 mins ago',
    channel: 'SMS',
    read: false,
    description: {
      en: 'High moisture saturation (89%) on Dima Hasao railway corridor. Mass SMS dispatched to 14,000 residents.',
      hi: 'डिमा हसाओ रेलवे गलियारे पर 89% नमी। 14,000 निवासियों को मास एसएमएस भेजा गया।',
    },
  },
  {
    id: 'alt-4',
    nodeId: 'node-khonoma',
    placeName: 'Khonoma Village',
    status: 'WATCH',
    timestamp: '18 mins ago',
    channel: 'LOCAL',
    read: false,
    description: {
      en: 'Sentinel Patrol #04 submitted verified ground tension rift photo (14.2mm) via offline mesh app.',
      hi: 'प्रहरी दल #04 ने ऑफ़लाइन मेश ऐप के माध्यम से भू-तनाव फोटो की पुष्टि की।',
    },
  },
];

export const generateRealtime7DayTrend = () => {
  const dates: string[] = [];
  const now = new Date();

  for (let i = 6; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);

    if (i === 0) {
      dates.push(`${d.getDate()} ${d.toLocaleString('en-GB', { month: 'short' })} (Today)`);
    } else {
      dates.push(`${d.getDate()} ${d.toLocaleString('en-GB', { month: 'short' })}`);
    }
  }

  return [
    { date: dates[0], score: 62 },
    { date: dates[1], score: 65 },
    { date: dates[2], score: 68 },
    { date: dates[3], score: 72 },
    { date: dates[4], score: 75 },
    { date: dates[5], score: 81 },
    { date: dates[6], score: 87 },
  ];
};

export const METHODOLOGY_STEPS: MethodologyStep[] = [
  {
    id: 1,
    stage: 'Ground Telemetry',
    description: 'Piezometers & MEMS Accelerometers',
    visual: 'ground-sensors.png',
    details: ['Ground piezometers, MEMS accelerometers, and soil moisture sensors measure millimeter-scale sub-surface creep.'],
    iconName: 'Radio',
  },
  {
    id: 2,
    stage: 'LoRaWAN Mesh',
    description: 'Solar Off-Grid Relays',
    visual: 'mesh-relays.png',
    details: ['Off-grid mesh nodes re-route telemetry packet streams around mountain peaks during severe monsoon grid blackouts.'],
    iconName: 'Network',
  },
  {
    id: 3,
    stage: 'InSAR Satellite Radar',
    description: 'ESA Sentinel-1 Coverage',
    visual: 'sar-radar.png',
    details: ['Free European Space Agency Sentinel-1 Synthetic Aperture Radar provides 6-day orbital deformation mapping across all 8 NER states.'],
    iconName: 'Cpu',
  },
  {
    id: 4,
    stage: 'AI Bayesian Fusion',
    description: 'Probabilistic Risk Scoring',
    visual: 'bayesian-model.png',
    details: ['Combines ground displacement, satellite interferometry, rainfall, and volunteer field photos into a 0–100 Risk Classification Index.'],
    iconName: 'CheckCircle2',
  },
  {
    id: 5,
    stage: 'Hyper-Local IVR Dispatch',
    description: 'Voice Calls in 19,569 Dialects',
    visual: 'ivr-phone-calls.png',
    details: ['Automated PSTN calls and Telegram voice alerts play emergency warning messages in Khasi, Assamese, Mizo, Nyishi, Garo, and Nagamese.'],
    iconName: 'Volume2',
  },
  {
    id: 6,
    stage: 'Explainable AI Feedback',
    description: 'Transparent Audit Trail',
    visual: 'xai-breakdown.png',
    details: ['Every alert includes an auditable XAI breakdown showing exact sensor weights, rainfall triggers, and pore pressure contributions.'],
    iconName: 'Sparkles',
  },
];

export const TECH_STACK_TILES: TechStackTile[] = [
  { category: 'Backend Telephony Dispatch', icon: 'Server', description: 'Native REST HTTP server for Twilio & Telegram Bot dispatching.' },
  { category: 'Frontend Engine', icon: 'Code', description: 'Blazing-fast responsive dashboard built with TypeScript.' },
  { category: 'Geographic Mapping', icon: 'Map', description: 'Open-source 100% keyless terrain and satellite radar tile mapping.' },
  { category: 'Styling', icon: 'Layout', description: 'Modern dark-mode dashboard with custom glassmorphism components.' },
];

export const RESEARCH_SOURCES: ResearchSource[] = [
  {
    badge: 'GSI 2024',
    source: 'Geological Survey of India (GSI)',
    detail: 'National Landslide Susceptibility Mapping (NLSM) program identifying high-hazard slope zones across Meghalaya, Nagaland, and Sikkim.',
    link: 'https://www.gsi.gov.in/',
  },
  {
    badge: 'ESA SAR',
    source: 'European Space Agency (ESA)',
    detail: 'Methodology for satellite InSAR mm-level slope creep monitoring over dense Himalayan vegetation.',
    link: 'https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-1',
  },
];

export const IMPACT_EVENTS: ImpactEvent[] = [
  {
    time: 'August 2026',
    title: 'Sohra Slope Creep Mitigation',
    subtitle: 'Sohra, East Khasi Hills, Meghalaya',
    statusBadge: 'Evacuation Successful',
    badgeType: 'SAFE',
  },
];
